### ISSUE TITLE
Namespace conflict in Diagrams.TwoD.Layout.Tree

### ISSUE THREAD

**Issue by tejon** [diagrams/diagrams-contrib#56]
D:\diagrams-contrib\src\Diagrams\TwoD\Layout\Tree.hs: line 187, column 18:
      Ambiguous occurrence `Empty'
        It could refer to either `Diagrams.TwoD.Layout.Tree.Empty',
                                 defined at src\Diagrams\TwoD\Layout\Tree.hs:182:16
                              or `Diagrams.Prelude.Empty',
                                 imported from `Diagrams.Prelude' at src\Diagrams\TwoD\Layout\Tree.hs:163:1-33
                                 (and originally defined in `Control.Lens.Empty')
    D:\diagrams-contrib\src\Diagrams\TwoD\Layout\Tree.hs: line 187, column 24:
      Ambiguous occurrence `Empty'
        It could refer to either `Diagrams.TwoD.Layout.Tree.Empty',
                                 defined at src\Diagrams\TwoD\Layout\Tree.hs:182:16
                              or `Diagrams.Prelude.Empty',
                                 imported from `Diagrams.Prelude' at src\Diagrams\TwoD\Layout\Tree.hs:163:1-33
                                 (and originally defined in `Control.Lens.Empty')

`Empty` is both defined locally (for the `BTree` type) and imported from `lens` via `Diagrams.Prelude`. This breaks compilation for me, both from Hackage (1.3.0.6) and GitHub (1.3.1).

**Comment by byorgey** [comment]
Thanks!  I wonder how we missed that.
