### ISSUE TITLE
Diagrams.TwoD.Grid provides gridWithHalves', but does not export GridOpts

### ISSUE THREAD

**Issue by jwiegley** [diagrams/diagrams-contrib#68]
https://hackage.haskell.org/package/diagrams-contrib-1.4.0.1/docs/Diagrams-TwoD-Grid.html

You can see that `GridOpts` is not a link, because there's no way to interact with it except to pass the default.

**Comment by byorgey** [comment]
Thanks!  It looks like there are several other things not exported from that module either.  Definitely an oversight. I wonder if the explicit export list was added as an afterthought.  In any case, I should be able to fix this soon.

**Comment by idontgetoutmuch** [comment]
Thanks for fixing this - I feel guilty that I hadn't since it was my contribution.

**Comment by byorgey** [comment]
No need to feel guilty!  To be honest I hadn't even looked to see who the original contributor was.  All are welcome to chip in and fix whatever needs fixing regardless of who originally contributed what.
