### ISSUE TITLE
GHC 8.2 compatible release

### ISSUE THREAD

**Issue by niteria** [diagrams/diagrams-contrib#70]
After 4f554eb93f528ecd1c95323e5b8c4c5a02426e16 this package builds with GHC 8.2.

Unfortunately bumping `cubicbezier` made this package depend transitively (through MemoTrie) on `newtype-generic`.

After https://github.com/jcristovao/newtype-generics/pull/14 is resolved (the maintainer hasn't responded to one pull request from Jan 2017 yet), this package builds and passes tests.

I think it should be safe to make the release anyway since MemoTrie doesn't put an upper bound on `newtype-generics`: https://hackage.haskell.org/package/MemoTrie

**Comment by byorgey** [comment]
Thanks.  Released version 1.4.1 to Hackage.
